services:

  db:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: studentmanagement
      POSTGRES_USER: sheranthap
      POSTGRES_PASSWORD: Test@123
    volumes:
      - pgdata:/var/lib/postgresql/data 

  federation-gateway:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - users
      - notifications

  users:
    image: users-service-image
    ports:
      - '3002:3002'

  notifications:
    image: notifications-service-image
    ports:
      - '3003:3003'

volumes:
  pgdata: